### ISSUE TITLE
不支持office文件的操作吗

### ISSUE THREAD

**Issue by XueFengWangNO1** [windy-purple/filejiami#1]
使用excel（xls）加解密失败

**Comment by windy-purple** [comment]
请提供更详细的信息

**Comment by XueFengWangNO1** [comment]
之前的描述不准确，Excel文件加密后可以使用Excel自带的解密框进行解密（Excel打开文件时输入密码能打开文件，如下图），而不是加密后文件乱码
![图片](https://user-images.githubusercontent.com/23218974/164899616-79965ad4-f419-4330-a0b2-5b6592e77848.png)

**Comment by windy-purple** [comment]
我不是很明白为什么你加密excel会出现这种现象，加密原理是读取文件的二进制，然后做rc4，之后写回文件，这跟文件格式无关，实在不行建议你更换其他方法
